### ISSUE TITLE
Arabic labels are displayed incorrectly

### ISSUE THREAD

**Issue by nouryf** [openmaptiles/openmaptiles#171]
Hi,

https://openmaptiles.github.io/osm-bright-gl-style/#11.93/33.4501/-7.5058

For city or town name, the labels is displayed in 'English/French' near 'Arabic' text. This last one is displayed incorrectly. In the example url above the town name is: Médiouna. 

Here is a correct label for the same town:

https://www.google.com/maps/@33.4509987,-7.5167079,14.95z

In 'OpenMaptiles' the text in Arabic appears to start from 'left to right' and the characters are not tied with each others. The Arabic language direction is right to left and the the characters composing a name are chained together.

May be this is a known issue ?

Thanks

**Comment by klokan** [comment]
Known issue - already fixed in TileServerGL. https://github.com/klokantech/tileserver-gl/issues/112 

We may fix it in the viewer above as well...

**Comment by nouryf** [comment]
Thanks for your response. I looked at https://www.mapbox.com/blog/supporting-arabic-and-hebrew/ and it states that MapBox GL js has a fix for this in 0.32.1. I edited my .html to point that version and I still see the same issue. May be some thing else is missing ?

**Comment by nouryf** [comment]
Found how to use the fix:
in the .html, I added:
mapboxgl.setRTLTextPlugin('mapbox-gl-rtl-text.js');

**Comment by klokan** [comment]
The recently reported problem is seems to be a problem of the KlokanTech Noto font - which should be fixed.

It is tracked in ticket: Missing characters in Arabic labels #194 

The problems reported here originally were related to a need to turn on the RTL plugin or upgrade to latest TileServer GL. This is solved.

**Comment by klokan** [comment]
Is there anybody willing to support the effort on fixing the font to contain all required Arabic glyphs?

**Comment by a-m-dev** [comment]
can you please provide a code sample of your index.html file that how to use 'mapbox-gl-rtl-text.js'  to convert labels in arabic text ?????
