### ISSUE TITLE
Buildings visible on z13 disappear on z14 

### ISSUE THREAD

**Issue by klokan** [openmaptiles/openmaptiles#225]
`#13.99/46.7507/7.6073`

![unnamed 10](https://cloud.githubusercontent.com/assets/59284/25276078/b6fc401e-2698-11e7-9a88-a98451bd3678.png)

`#14.01/46.7507/7.6073`

![unnamed 11](https://cloud.githubusercontent.com/assets/59284/25276081/b949a136-2698-11e7-9fa5-e571a0127d35.png)

This seems to be a bug in the schema. To be fixed in the next release, if possible.

**Comment by stirringhalo** [comment]
Issue might be in https://github.com/openmaptiles/openmaptiles/blob/master/layers/building/building.sql#L18 .  That function is used to properly handle complex building relations like the Eiffel tower. Might also be a bug in the tagging of those buildings.

They are tagged as building="house" or as in http://www.openstreetmap.org/way/246312545, building='yes' but part of the greater relation http://www.openstreetmap.org/relation/3327042 as building='house'. 

Likely related to https://github.com/openmaptiles/openmaptiles/issues/228 .

**Comment by stirringhalo** [comment]
Other more major issue is those buildings are in a relation with the road, and it's tagged as "street", leading to my building code not handling it. Fixing the relation handling will probably break 3D buildings. Thoughts?

https://www.openstreetmap.org/relation/3327042

**Comment by stirringhalo** [comment]
Buildings will need to be better handled, major undertaking. Pushing to 3.7

**Comment by stirringhalo** [comment]
@ImreSamu @klokan @jirik 
The only way I can see to fix this in Imposm3 is to change https://github.com/openmaptiles/openmaptiles/blob/master/layers/building/mapping.yaml#L153 to be any type and then perhaps filter from there. I will try it, I don't expect it to work.

**Comment by stirringhalo** [comment]
Trying again here https://github.com/openmaptiles/openmaptiles/pull/284

**Comment by stirringhalo** [comment]
Fixed, except for some artifacting. Tracking that issue separately.

**Comment by klokan** [comment]
This bug is CRITICAL!

It affects whole towns (such as Winterthur in Switzerland) and it is estimated that over 100k buildings gone missing in vector tiles probably! The original bug report in April sounds like only a few wrongly tagged buildings were wrong...

The bug was introduced in v3.5 during the changes on 3D buildings #128, and it was not fixed in time for the v3.6 release.

It is so critical we may need to do a new bug fix release v3.6.1 and generate the planet again to have this fixed in our production services ASAP.

Now we must verify the correctness of the code implementing the buildings in master - and run additional tests on the code which is suppose to fix this. Ideally, a similar bug should be caught by an automated (CI?) test in future.

@stirringhalo could you please comment on the status of the implementation in master?
Where is your ticket tracking the artifacting you mentioned - do you have any visual?

@MartinMikita please initiate the first tests, because @jirik is no holidays now.

**Comment by stirringhalo** [comment]
@klokan The artifacting is tracked here https://github.com/openmaptiles/openmaptiles/issues/286 . See #13.99/46.7507/7.6073 for a visual, haven't an import with it yet. 

I will look into Winterthur, Switzerland and see. Might still be more tagging issues, the buildings tagging with 3D can be a mess.

**Comment by stirringhalo** [comment]
@klokan I don't see any missing buildings. It shows up just fine. Those associatedStreets are very popular in certain regions http://www.openstreetmap.org/relation/1115276#map=17/47.50660/8.71904 and are accepted tagging.

This is probably an issue with associatedStreets, already fixed in https://github.com/openmaptiles/openmaptiles/pull/284 . 

So you will need a re-import and re-cache. That area has the multipolygon bug, but it may just be due to me using postserve.

**Comment by MartinMikita** [comment]
@stirringhalo We have tested rendering into MBTiles using your fix. Buildings are not missing now, but they are rendered as LineString, not Polygon, see en example:

![img](https://user-images.githubusercontent.com/2283182/27936771-e2b2858c-62b2-11e7-9b77-c93f41850e25.png)

Do you know about this? Is there any related ticket?

It seems this ticket can be closed as fixed now.

**Comment by stirringhalo** [comment]
I think it's related to https://github.com/openmaptiles/openmaptiles/issues/286
